name: Update adultfilter
on:
  push:
    paths-ignore:
    - '.github/**'
    - 'lists/**'
    - '*.txt'
    - '*.yaml'
    - '*.conf'
    - '*.txt'
    - '*.sh'
    - 'README.md'
  schedule:
    - cron: '30 13 * * *'

jobs:
  build-blocklist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3

      - name: Build blocklist
        uses: actions/checkout@v3
      - run: |
          chmod +x ./adultfilter-aggregator.sh
          ./adultfilter-aggregator.sh -o adultfilter.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "adultfilter"
          git push
