name: Update Blacklist
on:
  push:
    paths-ignore:
    - '.github/**'
    - 'README.md'
  schedule:
    - cron: '0 16 * * *'

jobs:
  build-blocklist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3

      - name: Build blocklist
        uses: actions/checkout@v3
      - run: |
          chmod +x ./blocklist-aggregator.sh
          ./blocklist-aggregator.sh
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "update blacklist"
          git push
